"""Curated, ATT&CK-mapped log-based IDS detection content (the "detection library").

This is *content*, not code: a maintained set of log-detection rules the agents
apply to decoded log lines. Rules are grouped by platform and MITRE ATT&CK tactic
and mix behavioural detections with known-threat / CVE / tooling signatures.

Telemetry sources the agent engine reads:
  Linux   : auth   (auth.log / secure)
            syslog (syslog / messages)
            auditd (/var/log/audit/audit.log — needs auditd + deploy/auditd rules)
            web    (nginx/apache access logs — SENTINEL_WEB_LOGS)
  Windows : winsec (Security event log)
            winsys (System event log)
            sysmon (Microsoft-Windows-Sysmon/Operational — needs Sysmon installed)

Rules that require extra telemetry (auditd, Sysmon, or Windows command-line
auditing) only fire once that telemetry is enabled — see docs/DETECTIONS.md.
`entity_group` = the regex capture group to correlate on (e.g. a source IP);
`threshold` > 1 alerts only after N matches per entity within `window_sec`.
"""
from __future__ import annotations

_IP = r"(\d{1,3}(?:\.\d{1,3}){3})"


def R(name, platform, source, pattern, event_type, severity, mitre, tactic,
      grp=0, thr=1, win=300, desc=""):
    return {
        "name": name, "platform": platform, "source": source, "pattern": pattern,
        "event_type": event_type, "severity": severity,
        "mitre": mitre if isinstance(mitre, list) else [mitre],
        "entity_group": grp, "threshold": thr, "window_sec": win,
        "description": (f"[{tactic}] " + desc) if tactic else desc,
    }


RULES = [
    # ===================== LINUX — Credential Access (TA0006) =====================
    R("ssh_bruteforce", "linux", "auth",
      r"Failed password for (?:invalid user )?\S+ from " + _IP,
      "BRUTE_FORCE_SOURCE", "HIGH", ["T1110"], "TA0006",
      grp=1, thr=5, win=300, desc="5+ failed SSH passwords from one source IP"),
    R("ssh_invalid_user", "linux", "auth",
      r"Invalid user \S+ from " + _IP,
      "SSH_INVALID_USER", "MEDIUM", ["T1110"], "TA0006",
      grp=1, thr=5, win=300, desc="Repeated logins for non-existent users (enumeration)"),
    R("pam_auth_failure", "linux", "auth",
      r"pam_unix\([^)]+:auth\): authentication failure.*rhost=" + _IP,
      "AUTH_FAILURE", "MEDIUM", ["T1110"], "TA0006",
      grp=1, thr=6, win=300, desc="Repeated PAM auth failures from one host (any service)"),
    R("su_failed", "linux", "auth",
      r"su(?:\[\d+\])?:.*FAILED su for \S+ by (\S+)",
      "SU_FAILED", "MEDIUM", ["T1078"], "TA0006",
      grp=1, thr=3, win=300, desc="Repeated failed su attempts by one user"),
    R("linux_shadow_access", "linux", "auditd",
      r'key="sentinel_identity"',
      "IDENTITY_FILE_MODIFIED", "HIGH", ["T1098", "T1003.008"], "TA0006",
      desc="Modification of /etc/shadow|passwd|group|sudoers (auditd identity watch, write-only)"),
    R("linux_cred_dump_tool", "linux", "any",
      r"(?i)\b(?:mimipenguin|lazagne|3snake|swap_digger)\b",
      "CREDENTIAL_DUMP_TOOL", "HIGH", ["T1003"], "TA0006",
      desc="Known Linux credential-dumping tool referenced"),

    # ===================== LINUX — Persistence (TA0003) =====================
    R("user_account_created", "linux", "auth",
      r"new user: name=(\S+?)[,\s]",
      "USER_ACCOUNT_CREATED", "HIGH", ["T1136.001"], "TA0003",
      grp=1, desc="A local user account was created"),
    R("user_account_deleted", "linux", "auth",
      r"userdel(?:\[\d+\])?: delete user '(\S+)'",
      "USER_ACCOUNT_DELETED", "MEDIUM", ["T1531"], "TA0040",
      grp=1, desc="A local user account was deleted"),
    R("user_added_privileged_group", "linux", "auth",
      r"add '(\S+)' to (?:shadow )?group '(?:sudo|admin|wheel|root|docker)'",
      "PRIVILEGED_GROUP_ADD", "HIGH", ["T1098"], "TA0003",
      grp=1, desc="A user was added to a privileged group"),
    R("password_changed", "linux", "auth",
      r"passwd\[\d+\]: password changed for (\S+)",
      "PASSWORD_CHANGED", "MEDIUM", ["T1098"], "TA0003",
      grp=1, desc="An account password was changed"),
    R("cron_edited", "linux", "syslog",
      r"crontab\[\d+\]: \((\S+)\) (?:REPLACE|BEGIN EDIT)",
      "CRON_EDITED", "MEDIUM", ["T1053.003"], "TA0003",
      grp=1, desc="A user's crontab was edited"),
    R("cron_suspicious_exec", "linux", "syslog",
      r"CRON\[\d+\]:.*(?:/tmp/|/dev/shm/|curl\s|wget\s|base64\s|bash\s+-c)",
      "CRON_SUSPICIOUS_EXEC", "HIGH", ["T1053.003"], "TA0003",
      desc="A cron job ran from a temp dir or fetched/decoded a payload"),
    R("at_job_scheduled", "linux", "syslog",
      r"atd\[\d+\]: \S+ \((\S+)\)",
      "AT_JOB_SCHEDULED", "LOW", ["T1053.002"], "TA0003",
      grp=1, desc="An at(1) job was scheduled"),
    R("linux_persistence_file", "linux", "auditd",
      r'key="sentinel_persistence"',
      "PERSISTENCE_FILE_WRITE", "HIGH", ["T1543.002", "T1037", "T1574.006"], "TA0003",
      desc="Write to a persistence path (systemd/cron/rc.local/ld.so.preload/authorized_keys) — auditd"),

    # ===================== LINUX — Privilege Escalation (TA0004) =====================
    R("sudo_auth_failure", "linux", "auth",
      r"sudo:.*authentication failure",
      "SUDO_AUTH_FAILURE", "MEDIUM", ["T1548.003"], "TA0004",
      thr=3, win=300, desc="Repeated sudo authentication failures"),
    R("pkexec_pwnkit", "linux", "any",
      r"(?i)pwnkit|CVE-2021-4034|GCONV_PATH=.*pkexec",
      "PRIVESC_EXPLOIT", "CRITICAL", ["T1068"], "TA0004",
      desc="PwnKit / CVE-2021-4034 pkexec local privilege escalation"),
    R("dirtypipe_dirtycow", "linux", "any",
      r"(?i)dirtypipe|dirty_pipe|CVE-2022-0847|dirtycow|CVE-2016-5195",
      "PRIVESC_EXPLOIT", "CRITICAL", ["T1068"], "TA0004",
      desc="Dirty Pipe / Dirty COW kernel LPE indicator"),
    R("setuid_shell", "linux", "any",
      r"chmod\s+(?:[24][0-7]{3}|\+s|u\+s)\s+\S*(?:/(?:ba)?sh|/dash|/python)",
      "SETUID_SHELL", "HIGH", ["T1548.001"], "TA0004",
      desc="Setuid bit set on a shell/interpreter"),

    # ===================== LINUX — Execution (TA0002) =====================
    R("reverse_shell_command", "linux", "any",
      r"(?:bash|sh)\s+-i\b.*(?:/dev/tcp/|0>&1)|nc(?:\.traditional)?\s+.*\s-e\s|mkfifo\s+\S+.*\|\s*(?:nc|/?bin/(?:ba)?sh)",
      "REVERSE_SHELL", "CRITICAL", ["T1059.004"], "TA0002",
      desc="Interactive reverse-shell one-liner in a log"),
    R("python_reverse_shell", "linux", "any",
      r"python[0-9.]*\s+-c\s+.{0,120}?(?:socket|pty).{0,120}?(?:connect|spawn|dup2)",
      "REVERSE_SHELL", "CRITICAL", ["T1059.006"], "TA0002",
      desc="Python one-liner reverse shell"),
    R("perl_ruby_reverse_shell", "linux", "any",
      r"(?:perl|ruby)\s+-e\s+.{0,120}?(?:IO::Socket|Socket|TCPSocket).{0,80}?(?:connect|exec|open)",
      "REVERSE_SHELL", "CRITICAL", ["T1059"], "TA0002",
      desc="Perl/Ruby reverse shell"),
    R("download_pipe_to_shell", "linux", "any",
      r"(?:curl|wget)\s+[^|]*\|\s*(?:sudo\s+)?(?:ba)?sh\b",
      "DOWNLOAD_EXEC", "HIGH", ["T1105"], "TA0002",
      desc="Download-and-execute cradle (curl/wget piped to a shell)"),
    R("base64_decode_exec", "linux", "any",
      r"base64\s+(?:-d|--decode)\b[^|]*\|\s*(?:ba)?sh\b|echo\s+[A-Za-z0-9+/]{40,}={0,2}\s*\|\s*base64",
      "OBFUSCATED_EXEC", "HIGH", ["T1027", "T1140"], "TA0005",
      desc="Base64-decoded payload piped to a shell"),
    R("linux_exec_suspicious_binary", "linux", "auditd",
      r'key="sentinel_exec_net"',
      "SUSPICIOUS_EXEC", "HIGH", ["T1059"], "TA0002",
      desc="Execution of nc/ncat/socat/nmap/etc. (auditd exec watch)"),

    # ===================== LINUX — Defense Evasion (TA0005) =====================
    R("history_tamper", "linux", "any",
      r"(?:rm\s+-f?\s*\S*\.bash_history|history\s+-c|unset\s+HISTFILE|export\s+HISTFILE=/dev/null|>\s*\S*\.bash_history)",
      "HISTORY_TAMPER", "MEDIUM", ["T1070.003"], "TA0005",
      desc="Shell history cleared / disabled"),
    R("log_tamper", "linux", "any",
      r"(?:>\s*/var/log/(?:auth|syslog|secure|messages)|truncate\s+-s\s*0\s+/var/log|journalctl\s+--vacuum|shred\s+.*/var/log)",
      "LOG_TAMPER", "HIGH", ["T1070.002"], "TA0005",
      desc="System log truncated / vacuumed / shredded"),
    R("defense_disable", "linux", "any",
      r"(?:setenforce\s+0|systemctl\s+stop\s+(?:auditd|apparmor|firewalld)|service\s+auditd\s+stop|auditctl\s+-e\s*0|ufw\s+disable)",
      "DEFENSE_DISABLE", "HIGH", ["T1562.001"], "TA0005",
      desc="Security control disabled (auditd/apparmor/selinux/firewall)"),
    R("linux_defense_evasion_audit", "linux", "auditd",
      r'key="sentinel_defense"',
      "AUDIT_CONFIG_CHANGE", "HIGH", ["T1562.001"], "TA0005",
      desc="Change to audit/security config (auditd defense watch)"),

    # ===================== LINUX — Discovery / Tooling (TA0007) =====================
    R("cloud_metadata_ssrf", "linux", "any",
      r"169\.254\.169\.254",
      "CLOUD_METADATA_ACCESS", "HIGH", ["T1552.005"], "TA0007",
      desc="Access to cloud instance metadata endpoint (SSRF / cred theft)"),
    R("linux_offensive_tool", "linux", "any",
      r"(?i)\b(?:linpeas|linenum|pspy|linux-exploit-suggester|unix-privesc-check|traitor|deepce|kubeletctl)\b",
      "OFFENSIVE_TOOL", "HIGH", ["T1588.002"], "TA0042",
      desc="Known Linux privilege-escalation / enumeration tool"),
    R("linux_c2_tunnel_tool", "linux", "any",
      r"(?i)\b(?:chisel|ligolo|frpc|frps|gost|revsocks|iodine|dnscat2|sshuttle)\b",
      "C2_TUNNEL_TOOL", "HIGH", ["T1090", "T1071"], "TA0011",
      desc="Known tunnelling / C2 relay tool"),

    # ===================== LINUX — Impact (TA0040) =====================
    R("cryptominer", "linux", "any",
      r"(?i)(?:xmrig|minerd|cpuminer|stratum\+tcp://|--donate-level|cryptonight|nanopool|supportxmr)",
      "CRYPTOMINER", "HIGH", ["T1496"], "TA0040",
      desc="Cryptocurrency miner indicator"),
    R("disk_wipe", "linux", "any",
      r"dd\s+if=/dev/(?:zero|urandom|null)\s+of=/dev/[sv]d[a-z]\b|mkfs\.\S+\s+/dev/[sv]d[a-z]\b",
      "DISK_WIPE", "CRITICAL", ["T1561.002"], "TA0040",
      desc="Raw write / reformat of a physical disk"),
    R("mass_ransom_note", "linux", "any",
      r"(?i)(?:README_FOR_DECRYPT|HOW_TO_DECRYPT|\.locked\b|\.encrypted\b|your files have been encrypted)",
      "RANSOMWARE_INDICATOR", "CRITICAL", ["T1486"], "TA0040",
      desc="Ransomware note / encrypted-extension indicator"),

    # ===================== WEB (Linux/Windows) — Initial Access (TA0001) =====================
    R("web_sql_injection", "any", "web",
      r"(?i)(union(?:\s|/\*.*?\*/)+select|\bor\s+1=1\b|sleep\(\d|information_schema|load_file\(|into\s+outfile)",
      "WEB_SQLI", "HIGH", ["T1190"], "TA0001",
      desc="SQL-injection signature in a web request"),
    R("web_path_traversal", "any", "web",
      r"(?i)(\.\./\.\./|/etc/passwd|%2e%2e%2f|\.\.%5c|/proc/self/environ)",
      "WEB_PATH_TRAVERSAL", "HIGH", ["T1083"], "TA0007",
      desc="Path-traversal / LFI attempt"),
    R("web_scanner_ua", "any", "web",
      r"(?i)(sqlmap|nikto|nmap|masscan|acunetix|nessus|dirbuster|gobuster|wpscan|nuclei|feroxbuster|ffuf|httpx)",
      "WEB_SCANNER", "MEDIUM", ["T1595.002"], "TA0043",
      desc="Known web scanner / fuzzer user-agent or tool"),
    R("web_log4shell", "any", "web",
      r"(?i)\$\{jndi:(?:ldap|ldaps|rmi|dns|iiop|nis|corba)://|\$\{(?:lower|upper|env|sys):",
      "WEB_LOG4SHELL", "CRITICAL", ["T1190"], "TA0001",
      desc="Log4Shell (CVE-2021-44228) JNDI lookup"),
    R("web_spring4shell", "any", "web",
      r"(?i)class\.module\.classLoader|class\.classLoader\.|%63lass%2e",
      "WEB_SPRING4SHELL", "HIGH", ["T1190"], "TA0001",
      desc="Spring4Shell (CVE-2022-22965) class-loader manipulation"),
    R("web_shellshock", "any", "web",
      r"\(\s*\)\s*\{\s*:\s*;\s*\}\s*;|\}\s*;\s*/bin/(?:ba)?sh",
      "WEB_SHELLSHOCK", "HIGH", ["T1190"], "TA0001",
      desc="Shellshock (CVE-2014-6271) bash function injection"),
    R("web_proxyshell_logon", "any", "web",
      r"(?i)/autodiscover/autodiscover\.json.*(?:@|PowerShell)|/mapi/nspi/|X-Rps-CAT=",
      "WEB_PROXYSHELL", "CRITICAL", ["T1190"], "TA0001",
      desc="Exchange ProxyShell/ProxyLogon exploitation pattern"),
    R("web_confluence_ognl", "any", "web",
      r"(?i)\$\{[^}]*(?:Runtime|ProcessBuilder|getRuntime)[^}]*\}|%24%7b.*exec",
      "WEB_OGNL_RCE", "CRITICAL", ["T1190"], "TA0001",
      desc="OGNL/EL injection RCE (e.g. Confluence CVE-2022-26134, Struts)"),
    R("web_webshell_request", "any", "web",
      r"(?i)/(?:c99|r57|wso|b374k|alfa|indoxploit|china[_-]?chopper|antsword|cmd|shell)\.(?:php|jsp|jspx|asp|aspx)\b",
      "WEB_WEBSHELL", "HIGH", ["T1505.003"], "TA0003",
      desc="Request to a known web-shell filename"),
    R("web_secret_file_probe", "any", "web",
      r"(?i)/(?:\.env(?:\.[a-z]+)?|\.git/(?:config|HEAD)|\.aws/credentials|\.ssh/id_[rd]sa|\.htpasswd|"
      r"wp-config\.php(?:\.(?:bak|old|save|txt)|~)?|config\.php\.(?:bak|old|save|swp)|\.svn/(?:entries|wc\.db)|"
      r"secrets?\.(?:ya?ml|json)|credentials\.json|\.DS_Store|\.npmrc|docker-compose\.ya?ml)\b",
      "WEB_SECRET_PROBE", "HIGH", ["T1552.001", "T1595.003"], "TA0043",
      desc="Probe for exposed secrets/config (.env, .git, .aws, wp-config, id_rsa) — credential-harvesting scan"),
    R("web_fake_browser_ua", "any", "web",
      r"(?:Mozlila/|Mozila/|\bBulid/|Moblie Safari)",
      "WEB_FAKE_UA", "MEDIUM", ["T1595", "T1071.001"], "TA0043",
      desc="Malformed/spoofed browser User-Agent (Mozlila/Bulid/Moblie typos) — known scanner/botnet fingerprint"),
    R("web_cms_admin_probe", "any", "web",
      r"(?i)/(?:wp-login\.php|wp-admin/|xmlrpc\.php|administrator/index\.php|phpmyadmin/|pma/|myadmin/|"
      r"manager/html|adminer\.php|actuator/(?:env|health|gateway|heapdump)|solr/|cgi-bin/)",
      "WEB_ADMIN_PROBE", "MEDIUM", ["T1595.003"], "TA0043",
      desc="CMS / admin-panel / mgmt-endpoint probing (wp-login, phpMyAdmin, actuator, manager) — reconnaissance"),
    R("web_exploit_scan", "any", "web",
      r"(?i)(?:/boaform/|/HNAP1|/GponForm/|/cgi-bin/(?:mainfunction\.cgi|luci|kerbynet|ViewLog|cgiServer)|"
      r"/vendor/phpunit/[^\s\"]*eval-stdin|/wp-content/plugins/[^\s\"?]*\.php\?|\?s=/index/think|"
      r"/owa/auth/[^\s\"]*\.js|\?XDEBUG_SESSION_START)",
      "WEB_EXPLOIT_SCAN", "HIGH", ["T1595.002", "T1190"], "TA0043",
      desc="Router/IoT/framework RCE exploit probe (boaform/HNAP/GponForm/phpunit/ThinkPHP) — active exploitation scan"),

    # ===================== WINDOWS — Credential Access (TA0006) =====================
    R("win_failed_logon", "windows", "winsec",
      r"EventID=4625\b.*Address=(\S+)",
      "BRUTE_FORCE_SOURCE", "HIGH", ["T1110"], "TA0006",
      grp=1, thr=5, win=300, desc="5+ failed Windows logons (4625) from one source"),
    R("win_account_lockout", "windows", "winsec",
      r"EventID=4740\b",
      "ACCOUNT_LOCKOUT", "MEDIUM", ["T1110"], "TA0006",
      desc="A Windows account was locked out (4740)"),
    R("win_kerberoast", "windows", "winsec",
      r"EventID=4769\b.*TktEnc=0x17\b",
      "KERBEROASTING", "HIGH", ["T1558.003"], "TA0006",
      desc="Kerberos service ticket requested with RC4 (kerberoasting, 4769/0x17)"),
    R("win_lsass_dump_tool", "windows", "winsec",
      r"(?i)EventID=4688\b.*Cmd=.*(?:mimikatz|sekurlsa|lsadump|comsvcs\.dll.*MiniDump|procdump(?:64)?\s.*lsass|nanodump|dumpert)",
      "CREDENTIAL_DUMPING", "CRITICAL", ["T1003.001"], "TA0006",
      desc="LSASS credential-dumping tool/technique (4688 cmdline)"),

    # ===================== WINDOWS — Persistence / Priv-Esc (TA0003/TA0004) =====================
    R("win_user_created", "windows", "winsec",
      r"EventID=4720\b",
      "USER_ACCOUNT_CREATED", "HIGH", ["T1136.001"], "TA0003",
      desc="A Windows user account was created (4720)"),
    R("win_user_deleted", "windows", "winsec",
      r"EventID=4726\b",
      "USER_ACCOUNT_DELETED", "MEDIUM", ["T1531"], "TA0040",
      desc="A Windows user account was deleted (4726)"),
    R("win_added_to_privileged_group", "windows", "winsec",
      r"EventID=(?:4728|4732|4756)\b",
      "PRIVILEGED_GROUP_ADD", "HIGH", ["T1098"], "TA0003",
      desc="Member added to a security-enabled/admin group (4728/4732/4756)"),
    R("win_scheduled_task_created", "windows", "winsec",
      r"EventID=4698\b",
      "SCHEDULED_TASK_CREATED", "HIGH", ["T1053.005"], "TA0003",
      desc="A scheduled task was created (4698)"),
    R("win_service_installed", "windows", "winsys",
      r"EventID=7045\b",
      "SERVICE_INSTALLED", "MEDIUM", ["T1543.003"], "TA0003",
      desc="A new Windows service was installed (7045)"),
    R("win_special_privileges", "windows", "winsec",
      r"EventID=4672\b.*Subject=(?!SYSTEM|LOCAL SERVICE|NETWORK SERVICE|-)(\S+)",
      "SPECIAL_PRIVILEGES_ASSIGNED", "MEDIUM", ["T1078"], "TA0004",
      grp=1, desc="Admin/special privileges assigned to a non-system logon (4672)"),

    # ===================== WINDOWS — Defense Evasion (TA0005) =====================
    R("win_log_cleared", "windows", "winsec",
      r"EventID=1102\b",
      "AUDIT_LOG_CLEARED", "HIGH", ["T1070.001"], "TA0005",
      desc="The Windows Security audit log was cleared (1102)"),
    R("win_audit_policy_changed", "windows", "winsec",
      r"EventID=4719\b",
      "AUDIT_POLICY_CHANGED", "HIGH", ["T1562.002"], "TA0005",
      desc="System audit policy was changed (4719)"),
    R("win_defender_tamper", "windows", "winsec",
      r"(?i)EventID=4688\b.*Cmd=.*(?:Set-MpPreference\s+.*-Disable|Add-MpPreference\s+.*ExclusionPath|sc(?:\.exe)?\s+.*stop\s+WinDefend|netsh\s+advfirewall\s+set\s+.*state\s+off)",
      "DEFENSE_TAMPER", "HIGH", ["T1562.001"], "TA0005",
      desc="Defender/firewall tampering via command line (4688)"),

    # ===================== WINDOWS — Execution / LOLBins (TA0002) =====================
    R("win_lolbin_process", "windows", "winsec",
      r"(?i)EventID=4688\b.*Process=.*\\(?:mshta|wscript|cscript|regsvr32|rundll32|certutil|bitsadmin|msbuild|installutil|wmic)\.exe",
      "LOLBIN_PROCESS", "HIGH", ["T1218"], "TA0005",
      desc="A living-off-the-land binary was launched (4688)"),
    R("win_encoded_powershell", "windows", "winsec",
      r"(?i)EventID=4688\b.*Cmd=.*(?:-enc\b|-EncodedCommand|FromBase64String|IEX\b|Invoke-Expression|-nop\b.*-w\s*hidden|DownloadString)",
      "ENCODED_POWERSHELL", "CRITICAL", ["T1059.001"], "TA0002",
      desc="Encoded/obfuscated PowerShell in a process command line (4688)"),
    R("win_lolbin_download", "windows", "winsec",
      r"(?i)EventID=4688\b.*Cmd=.*(?:certutil.*-urlcache|bitsadmin.*/transfer|Invoke-WebRequest|curl\s+.*http|wget\s+.*http)",
      "LOLBIN_DOWNLOAD", "HIGH", ["T1105"], "TA0011",
      desc="A LOLBin was used to download a payload (4688)"),
    R("win_wmic_process_call", "windows", "winsec",
      r"(?i)EventID=4688\b.*Cmd=.*wmic.*process\s+call\s+create",
      "WMIC_EXECUTION", "HIGH", ["T1047"], "TA0002",
      desc="Remote/lateral execution via wmic process call create (4688)"),
    R("win_psexec", "windows", "any",
      r"(?i)(?:EventID=4688\b.*Cmd=.*psexec|Service=PSEXESVC|File=.*PSEXESVC)",
      "PSEXEC_EXECUTION", "HIGH", ["T1569.002", "T1021.002"], "TA0008",
      desc="PsExec service execution (lateral movement)"),

    # ===================== WINDOWS — Discovery / Lateral (TA0007/TA0008) =====================
    R("win_domain_recon", "windows", "winsec",
      r"(?i)EventID=4688\b.*Cmd=.*(?:net\s+group\s+\"domain admins\"|net\s+user\s+/domain|nltest\s+/domain_trusts|whoami\s+/all|net\s+localgroup\s+administrators)",
      "DOMAIN_RECON", "MEDIUM", ["T1087"], "TA0007",
      desc="Active-Directory reconnaissance commands (4688)"),
    R("win_bloodhound", "windows", "winsec",
      r"(?i)EventID=4688\b.*Cmd=.*(?:sharphound|bloodhound|-CollectionMethod|invoke-bloodhound)",
      "AD_ENUMERATION", "HIGH", ["T1087.002"], "TA0007",
      desc="BloodHound / SharpHound AD enumeration (4688)"),
    R("win_rdp_logon", "windows", "winsec",
      r"EventID=4624\b.*LogonType=10\b",
      "RDP_LOGON", "MEDIUM", ["T1021.001"], "TA0008",
      desc="Interactive RDP logon (4624 type 10)"),

    # ===================== WINDOWS — Impact (TA0040) =====================
    R("win_shadow_copy_delete", "windows", "winsec",
      r"(?i)EventID=4688\b.*Cmd=.*(?:vssadmin\s+delete\s+shadows|wmic\s+shadowcopy\s+delete|bcdedit.*recoveryenabled\s+no|wbadmin\s+delete\s+catalog)",
      "RANSOMWARE_PREP", "CRITICAL", ["T1490"], "TA0040",
      desc="Shadow-copy / backup deletion (ransomware precursor, 4688)"),

    # ===================== WINDOWS — Sysmon (rich endpoint telemetry) =====================
    R("sysmon_lsass_access", "windows", "sysmon",
      r"EventID=10\b.*Target=.*\\lsass\.exe",
      "LSASS_ACCESS", "CRITICAL", ["T1003.001"], "TA0006",
      desc="Process accessed LSASS memory (credential dumping, Sysmon 10)"),
    R("sysmon_office_spawns_shell", "windows", "sysmon",
      r"(?i)EventID=1\b.*Parent=.*\\(?:winword|excel|powerpnt|outlook|mspub|onenote)\.exe.*Image=.*\\(?:cmd|powershell|wscript|cscript|mshta|rundll32)\.exe",
      "OFFICE_SPAWNS_SHELL", "HIGH", ["T1566.001"], "TA0001",
      desc="Office application spawned a shell/script host (Sysmon 1)"),
    R("sysmon_server_spawns_shell", "windows", "sysmon",
      r"(?i)EventID=1\b.*Parent=.*\\(?:w3wp|sqlservr|httpd|tomcat\d*|nginx)\.exe.*Image=.*\\(?:cmd|powershell)\.exe",
      "WEBSHELL_EXECUTION", "HIGH", ["T1505.003"], "TA0002",
      desc="Web/DB server process spawned a shell (webshell / RCE, Sysmon 1)"),
    R("sysmon_encoded_powershell", "windows", "sysmon",
      r"(?i)EventID=1\b.*Cmd=.*(?:-enc\b|-EncodedCommand|FromBase64String|IEX\b|Invoke-Expression|-nop\b.*-w\s*hidden|DownloadString)",
      "ENCODED_POWERSHELL", "CRITICAL", ["T1059.001"], "TA0002",
      desc="Encoded/obfuscated PowerShell (Sysmon 1)"),
    R("sysmon_remote_thread", "windows", "sysmon",
      r"EventID=8\b",
      "PROCESS_INJECTION", "HIGH", ["T1055"], "TA0005",
      desc="CreateRemoteThread — process injection (Sysmon 8)"),
    R("sysmon_cobaltstrike_pipe", "windows", "sysmon",
      r"(?i)EventID=1[78]\b.*Pipe=.*\\(?:MSSE-|postex_|status_|msagent_|\d{4}\.\d{3})",
      "C2_NAMED_PIPE", "CRITICAL", ["T1055"], "TA0011",
      desc="Cobalt Strike / Meterpreter default named pipe (Sysmon 17/18)"),
    R("sysmon_startup_persistence", "windows", "sysmon",
      r"(?i)EventID=11\b.*File=.*\\Start Menu\\Programs\\Startup\\",
      "STARTUP_PERSISTENCE", "HIGH", ["T1547.001"], "TA0003",
      desc="File dropped into a Startup folder (Sysmon 11)"),
    R("sysmon_run_key_persistence", "windows", "sysmon",
      r"(?i)EventID=1[23]\b.*Reg=.*\\CurrentVersion\\Run",
      "RUN_KEY_PERSISTENCE", "HIGH", ["T1547.001"], "TA0003",
      desc="Autorun registry Run-key set (Sysmon 12/13)"),
    R("sysmon_metadata_connection", "windows", "sysmon",
      r"EventID=3\b.*Dst=169\.254\.169\.254\b",
      "CLOUD_METADATA_ACCESS", "HIGH", ["T1552.005"], "TA0007",
      desc="Network connection to cloud metadata endpoint (Sysmon 3)"),
    R("sysmon_susp_dns", "windows", "sysmon",
      r"(?i)EventID=22\b.*Query=.*\.(?:top|xyz|tk|gq|ml|cf|duckdns\.org|ngrok\.io|zip|mov)\b",
      "SUSPICIOUS_DNS", "MEDIUM", ["T1071.004"], "TA0011",
      desc="DNS query to a high-abuse TLD / dynamic-DNS / tunnelling domain (Sysmon 22)"),
    R("sysmon_process_tampering", "windows", "sysmon",
      r"(?i)EventID=25\b",
      "PROCESS_TAMPERING", "HIGH", ["T1055.012"], "TA0005",
      desc="Process hollowing / image tampering / herpaderping (Sysmon 25)"),
    R("sysmon_injection_from_lolbin", "windows", "sysmon",
      r"(?i)EventID=8\b.*Source=.*\\(?:powershell|pwsh|rundll32|regsvr32|mshta|wscript|cscript|winword|excel)\.exe",
      "PROCESS_INJECTION_LOLBIN", "HIGH", ["T1055.001"], "TA0005",
      desc="CreateRemoteThread originating from a script host / LOLBin (Sysmon 8)"),

    # ===================== WINDOWS — ETW operational channels (source="etw") =====================
    # ETW-backed event-log channels beyond Security/System/Sysmon: PowerShell script-block
    # logging, WMI-Activity, and Defender. Consumed via the same reader; require the channels
    # enabled (the agent's telemetry provisioning does this). See docs/DETECTIONS.md.
    R("etw_powershell_obfuscation", "windows", "etw",
      r"(?i)EventID=4104\b.*Script=.*(?:FromBase64String|-enc\b|-EncodedCommand|\bIEX\b|Invoke-Expression|DownloadString|DownloadData|Net\.WebClient|Invoke-WebRequest|Reflection\.Assembly|\[char\]|-join)",
      "POWERSHELL_OBFUSCATION", "HIGH", ["T1059.001", "T1027"], "TA0002",
      desc="Obfuscated/encoded PowerShell captured by script-block logging (ETW PowerShell/Operational 4104)"),
    R("etw_wmi_persistence", "windows", "etw",
      r"(?i)EventID=(?:5860|5861)\b",
      "WMI_EVENT_SUBSCRIPTION", "HIGH", ["T1546.003"], "TA0003",
      desc="WMI permanent event consumer / subscription bound — persistence (ETW WMI-Activity/Operational)"),
    R("etw_defender_malware", "windows", "etw",
      r"(?i)EventID=(?:1006|1015|1116|1117)\b",
      "DEFENDER_MALWARE", "HIGH", ["T1204"], "TA0002",
      desc="Microsoft Defender detected/acted on malware (ETW Windows Defender/Operational)"),
    R("etw_defender_tamper", "windows", "etw",
      r"(?i)EventID=(?:5001|5010|5012)\b",
      "DEFENDER_DISABLED", "HIGH", ["T1562.001"], "TA0005",
      desc="Microsoft Defender real-time / scanning protection disabled (ETW Windows Defender/Operational)"),

    # ===================== LINUX — eBPF kernel behaviour (source="ebpf") =====================
    # Matched by the agent's bpftrace engine against compact `TYPE|pid|uid|comm|detail`
    # lines. Kernel ground-truth — catches fileless / no-log execution that log rules miss.
    R("ebpf_reverse_shell", "linux", "ebpf",
      r"^EXEC\|.*(?:/dev/tcp/|/dev/udp/|\b(?:bash|sh|zsh) -i\b|\bnc(?:at)? .*-e |socat\b.*\bexec)",
      "REVERSE_SHELL_EXEC", "CRITICAL", ["T1059.004"], "TA0002",
      desc="eBPF: exec of an interactive/redirected reverse shell (/dev/tcp, bash -i, nc -e, socat exec)"),
    R("ebpf_download_exec", "linux", "ebpf",
      r"^EXEC\|.*\b(?:bash|sh|zsh) +-c\b.*\b(?:curl|wget|fetch)\b",
      "DOWNLOAD_EXEC", "HIGH", ["T1105"], "TA0002",
      desc="eBPF: shell -c invoking curl/wget (download-and-execute cradle)"),
    R("ebpf_script_reverse_shell", "linux", "ebpf",
      r"^EXEC\|.*\b(?:python[0-9.]*|perl|ruby|php)\b.*\ -c\b.*(?:socket|/dev/tcp|pty\.spawn|fsockopen|IO\.popen)",
      "SCRIPT_REVERSE_SHELL", "CRITICAL", ["T1059.006"], "TA0002",
      desc="eBPF: interpreter one-liner reverse shell (python/perl/ruby/php -c with socket/pty)"),
    R("ebpf_offensive_tool", "linux", "ebpf",
      r"^EXEC\|.*\b(?:nmap|masscan|ncat|socat|hydra|medusa|nikto|sqlmap|responder|chisel|ligolo)\b",
      "OFFENSIVE_TOOL_EXEC", "MEDIUM", ["T1046"], "TA0007",
      desc="eBPF: execution of a known offensive/recon tool"),
    R("ebpf_ptrace_inject", "linux", "ebpf",
      r"^PTRACE\|.*request=(?:4|5)\b",
      "PROCESS_INJECTION_PTRACE", "HIGH", ["T1055.008"], "TA0005",
      desc="eBPF: ptrace POKETEXT/POKEDATA — writing into another process's memory (injection)"),
    R("ebpf_kernel_module_load", "linux", "ebpf",
      r"^MODLOAD\|",
      "KERNEL_MODULE_LOAD", "MEDIUM", ["T1547.006"], "TA0003",
      desc="eBPF: a kernel module was loaded at runtime (init_module/finit_module) — possible LKM rootkit"),
    R("ebpf_memfd_fileless", "linux", "ebpf",
      r"^MEMFD\|",
      "FILELESS_MEMFD", "MEDIUM", ["T1620"], "TA0005",
      desc="eBPF: memfd_create — anonymous in-memory file, a common fileless-payload primitive"),
    R("ebpf_wx_mprotect", "linux", "ebpf",
      r"^WX\|",
      "WX_MPROTECT", "HIGH", ["T1055"], "TA0005",
      desc="eBPF: mprotect made a region simultaneously WRITE+EXEC (W^X violation) — shellcode / code injection"),
]
